### ISSUE TITLE
The data couldn’t be read because it isn’t in the correct format

### ISSUE THREAD

**Issue by lucifer001** [EnjoySR/ESJsonFormat-Xcode#1]
我们后端返回的这种数据，没法用啊。
{
    data =     {
        album =         (
        );
        "attr_num" = 10;
        "dynamic_num" = 20;
        "fans_num" = 9;
        "friends_num" = 5;
        hobby = "";
        integral = 102;
        level = 0;
        nickname = "\U8f7b\U8214\U6307\U5c16";
        rmb = 96936;
        signature = "";
    };
    msg = success;
    result = 1;
}

**Comment by EnjoySR** [comment]
这个不是一个正确的json哟，json校验:http://www.kjson.com/

**Comment by lucifer001** [comment]
哦，必须是json啊 ，这个是json解析后的数据字典

**Comment by XVXVXXX** [comment]
你好，我觉得你这个插件，应该也能接受: 冒号前面的key不带 ""，因为比如我用chrome的插件jsonview(很常用)去查看这个json，那么jsonView展示的json就是冒号前面没有""的，这时候用你这个插件就会报错了：The data couldn’t be read because it isn’t in the correct format. 你可以考虑你一下要不要加这个功能。

**Comment by EnjoySR** [comment]
嗯嗯。如果没有其他疑问的话我就close了哦？谢谢你的关注。
