### ISSUE TITLE
不是json正规格式就直接卡死，xcode只能强退？？？

### ISSUE THREAD

**Issue by zdrjson** [EnjoySR/ESJsonFormat-Xcode#11]

**Comment by zdrjson** [comment]
{"code":0,"data":[{"picUrl":"/banner/images/3_0/1.jpg"},{"picUrl":"/banner/images/3_0/2.jpg"},{"picUrl":"/banner/images/3_0/3.jpg"},{"picUrl":"/banner/images/3_0/4_1.jpg"}],"pages":0,"msg":""} 
这个格式你不能认识吗？

**Comment by EnjoySR** [comment]
如果JSON不是正规json的话，会提示The data couldn’t be read because it isn’t in the correct format.你上述的JSON是可以解析的。你更新插件之后再试试看看

**Comment by zdrjson** [comment]
刚刚更新的，期待你能自己转成json正规格式!

**Comment by EnjoySR** [comment]
现在能用了嘛？

**Comment by zdrjson** [comment]
The operation couldn't be completed (Current state is not edit! error 0).

**Comment by EnjoySR** [comment]
当前不是编辑状态，不能执行操作。你当前没有打开具体的文件吧？只停留在Welcome to Xcode 这个页面就在使用了吧？

**Comment by zdrjson** [comment]
不行，你打都打不开了？

**Comment by EnjoySR** [comment]
你得进入到具体Model文件里面去再使用呃，你是在什么地方(Xcode打开的哪个页面)去调用插件的

**Comment by zdrjson** [comment]
1.键盘enter 键只是换行效果？
2.属性中关键字比如 id  能像 MJExtension 中转---->
+(NSDictionary *)replacedKeyFromPropertyName
{
    return @{@"ID":@"id"};
}
???
3.重新按shift 和control 和J ,里面的数据都没有了？

**Comment by EnjoySR** [comment]
1.在JSON输入窗口Enter键盘就是换行效果
2.关键字过滤这个功能还没有做
3.数据不会保存上一次的。
