### ISSUE TITLE
麻烦增加初始化方法

### ISSUE THREAD

**Issue by uiue** [EnjoySR/ESJsonFormat-Xcode#12]
麻烦增加初始化方法, 谢谢.  只生成属性仅完成了一半的工作. model类应该增加一个传入键值对初始化方法,或者传入数组初始化.

**Comment by EnjoySR** [comment]
推荐使用@CoderMJLee 的[MJExtension](https://github.com/CoderMJLee/MJExtension)中的objectWithKeyValues这个方法，一行代码就可以实现你如上所说的那个功能。
