### ISSUE TITLE
支持xcode6.4

### ISSUE THREAD

**Issue by daqiangge** [EnjoySR/ESJsonFormat-Xcode#14]

**Comment by daqiangge** [comment]
支持xcode6.4吗？为啥运行了，不管用？

**Comment by EnjoySR** [comment]
Xcode 6.4是支持的，其他插件在你那个Xcode能使用码？如果能使用的话，你再重新卸载我的插件重装一次试试。

**Comment by daqiangge** [comment]
卸载重装了。点击Window里的ESJsonFormat后就没反应了。

**Comment by EnjoySR** [comment]
呃，还不行吗？

**Comment by EggmanQi** [comment]
我安装了之后再启动xcode还是看不到有 ESJsonFormat 的选项

**Comment by EnjoySR** [comment]
@EggmanQi 你电脑上的其他插件正常嘛？你通过[Alcatraz](http://alcatraz.io/)装试试看看

**Comment by EggmanQi** [comment]
@EnjoySR 过了几个小时后它出来了。。。。

**Comment by daqiangge** [comment]
我的不管用，那个输入json数据的面板就是出不来，卸载，重启都不行

**Comment by EnjoySR** [comment]
@daqiangge 你通过[Alcatraz](http://alcatraz.io/)装试试看看

**Comment by cocsmile** [comment]
通过Alcatraz remove 再intall 然后重启Xcode6.4 会弹框 选择 LoadBoundles 就可以了

**Comment by EggmanQi** [comment]
又来了~~~~~
Version 6.4 (6E35b) 使用后会崩溃，输入的数据是Readme中‘复杂模型’数据，然后弹出窗口检测到数据嵌套之后，再弹出的小窗口只有输入框没有按钮，点enter xcode就会崩溃。

**Comment by EnjoySR** [comment]
@EggmanQi 你更新下插件再试试？

**Comment by weizhangCoder** [comment]
xcode是6.3.2的一直没发用这个插件，别的插件都没有问题，就是window里一直没有出现ESJson那一项。

**Comment by EnjoySR** [comment]
@weizhangCoder 你卸载插件，然后重启Xcode，然后再重装，再重启Xcode，启动的时候有一个弹出窗口，选择Load Bundle

**Comment by weizhangCoder** [comment]
装上了，试了一下第二个复杂的数据，就会出现卡死，必须结束xcode， 提示“lmplement method objcetClassInArray for MJExtension”

**Comment by EnjoySR** [comment]
@weizhangCoder 能截一个图贴上来么

**Comment by weizhangCoder** [comment]
是否又看到我给你邮件回的截图。

**Comment by renyufei8023** [comment]
需要更新了，xcode6.4安装成功无法正常使用

**Comment by EnjoySR** [comment]
@renyufei8023 安装成功之后，重启xcode的时候，弹出了一个选择窗口，你选择了load bundle了没有呐，如果不是选择的这个，重新卸载安装。插件是支持Xcode 6.4的

**Comment by renyufei8023** [comment]
我从新用Alcatraz这个安装的  已经可以使用了额

**Comment by EnjoySR** [comment]
@renyufei8023 嗯嗯,谢谢您的支持.先close掉这个
