### ISSUE TITLE
复杂JSON XCode崩溃

### ISSUE THREAD

**Issue by JomyWu** [EnjoySR/ESJsonFormat-Xcode#17]
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
Sending enterButtonClick: to <ESInputJsonController: 0x7fc23e149c90> from <NSButton: 0x7fc23f30c1b0>
ProductBuildVersion: 6D570
UNCAUGHT EXCEPTION (NSGenericException): **\* Collection <__NSDictionaryM: 0x7fc23e93dbb0> was mutated while being enumerated.
UserInfo: (null)
Hints: 
  0: Sending enterButtonClick: to <ESInputJsonController: 0x7fc23e149c90> from <NSButton: 0x7fc23f30c1b0>
Backtrace:
  0  0x00007fff8e0b6024 __exceptionPreprocess (in CoreFoundation)
  1  0x000000010974f184 DVTFailureHintExceptionPreprocessor (in DVTFoundation)
  2  0x00007fff9335d76e objc_exception_throw (in libobjc.A.dylib)
  3  0x00007fff8e0b58d5 __NSFastEnumerationMutationHandler (in CoreFoundation)
  4  0x0000000119056f8a -[ESInputJsonController dealNameWithDictionary:] at /Users/Jomy/Desktop/ESJsonFormat-Xcode-master/ESJsonFormat/Controller/ESInputJsonController.m:100 (in ESJsonFormat)
  5  0x0000000119056a45 -[ESInputJsonController enterButtonClick:] at /Users/Jomy/Desktop/ESJsonFormat-Xcode-master/ESJsonFormat/Controller/ESInputJsonController.m:65 (in ESJsonFormat)
  6  0x00007fff97d8acd7 _os_activity_initiate (in libsystem_trace.dylib)
  7  0x00007fff8b1b9fb1 -[NSApplication sendAction:to:from:](in AppKit)
  8  0x0000000109cd280d __37-[DVTApplication sendAction:to:from:]_block_invoke (in DVTKit)
  9  0x000000010974eec2 DVTInvokeWithFailureHint (in DVTFoundation)
 10  0x0000000109b9b0ce -[DVTApplication sendAction:to:from:](in DVTKit)
 11  0x00007fff8b1cfa46 -[NSControl sendAction:to:](in AppKit)
 12  0x00007fff8b1cf962 __26-[NSCell _sendActionFrom:]_block_invoke (in AppKit)
 13  0x00007fff97d8acd7 _os_activity_initiate (in libsystem_trace.dylib)
 14  0x00007fff8b1cf8bf -[NSCell _sendActionFrom:](in AppKit)
 15  0x00007fff97d8acd7 _os_activity_initiate (in libsystem_trace.dylib)
 16  0x00007fff8b1cddb3 -[NSCell trackMouse:inRect:ofView:untilMouseUp:](in AppKit)
 17  0x00007fff8b22645f -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:](in AppKit)
 18  0x00007fff8b1cc466 -[NSControl mouseDown:](in AppKit)
 19  0x00007fff8b7362fc -[NSWindow _reallySendEvent:isDelayedEvent:](in AppKit)
 20  0x00007fff8b0c5d76 -[NSWindow sendEvent:](in AppKit)
 21  0x00007fff8b0c2312 -[NSApplication sendEvent:](in AppKit)
 22  0x000000010a7cb494 -[IDEApplication sendEvent:](in IDEKit)
 23  0x00007fff8afebc68 -[NSApplication run](in AppKit)
 24  0x00007fff8af68354 NSApplicationMain (in AppKit)
 25  0x00007fff95b845c9 start (in libdyld.dylib)

**Comment by EnjoySR** [comment]
能把您的JSON 复制出来我看看吗？

**Comment by JomyWu** [comment]
{
  "status": "ok", 
  "product": "minutes_prec", 
  "server_time": 1436327865.636728, 
  "descript_now": "", 
  "temp": 30, 
  "skycon": "FOG", 
  "summary": "\u672a\u6765\u4e00\u5c0f\u65f6\u4e0d\u4f1a\u4e0b\u96e8\uff0c\u653e\u5fc3\u51fa\u95e8\u5427", 
  "source": "radar", 
  "location": [
    39.93, 
    116.39
  ], 
  "nearest_rain": {
    "distance": 9979.035639412998, 
    "direction": 90.00098419189453, 
    "intensity": 0.0
  }, 
  "dataseries": [
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0, 
    0.0
  ]
}

**Comment by EnjoySR** [comment]
好，谢谢你的反馈，修复之后我在此回复你。烦劳您到时候更新下。

**Comment by JomyWu** [comment]
感谢你 速度太快了

**Comment by EnjoySR** [comment]
已修复，烦劳更新，感谢你的持续关注~
