### ISSUE TITLE
可以增加泛型的支持吗？

### ISSUE THREAD

**Issue by ghost** [EnjoySR/ESJsonFormat-Xcode#19]
XCode7 中objective－C也可以有泛型了

**Comment by EnjoySR** [comment]
可以。我抽时间把这个功能完善一下，然后在这回复您！谢谢你的关注

**Comment by ghost** [comment]
这个解析不了 NSDictionary 么？好像直接变成一个新的类了。

**Comment by ghost** [comment]
我尝试着加了下泛型，在 ESInputJsonController.m 这个文件中（见附件的 GenericType 分支）。不知道这样子和你写的会不会有冲突。
做了个简单的测试，暂时没有发现问题。

对于你之前的代码就是发现两种情况无法生成：
1.我之前问的 NSDictionary 的创建；
2.如果是复杂的模型，比如数组里面套数组；

**Comment by EnjoySR** [comment]
@Xiaolong-Jin 你说的解析NSDictionary这个解析不了是什么意思，能把格式贴上来我看看吗？然后我看了你好像传了一张图片上来，，我这怎么看不到。。。还有谢谢你对代码的贡献，，这几天特别忙没空更新不好意思呐  。。呃，附件在哪儿

**Comment by ghost** [comment]
我给你发的是邮件，没想到是和这里关联的。
不过这里好像不支持图片和附件。第一次用github，我看看有没有私聊的东东

我发你的gmail邮箱了😊

**Comment by EnjoySR** [comment]
好的，非常感谢。

**Comment by EnjoySR** [comment]
已添加泛型的支持。关于你的那个JSON里面是数组套数组，而每个数组里面都是基本数据类型的，解析出来按现在的结果应该是正常的。谢谢你的反馈。如果有其他的建议请你issues我
