### ISSUE TITLE
强烈要求Swift

### ISSUE THREAD

**Issue by androidcn** [EnjoySR/ESJsonFormat-Xcode#2]
Swift

**Comment by EnjoySR** [comment]
支持swift功能待我开发完成我第一时间通知你，请持续关注，谢谢你。

**Comment by androidcn** [comment]
在这做Close 或者 Comment即可 谢谢 @EnjoySR

**Comment by EnjoySR** [comment]
支持Swift已完成，请下载测试。先close掉这个，有问题请继续Issues我
