### ISSUE TITLE
两点用得不是很爽

### ISSUE THREAD

**Issue by ghost** [EnjoySR/ESJsonFormat-Xcode#22]
您好，首先谢谢贡献一个这么好的json生成模型的工具，让我又可以偷点懒了，O(∩_∩)O哈哈~。我说说使用过程中两点不是很爽的地方：1、模型属性中无对象属性的时候也会生成空@class声明；2、模型中有数组属性最好可以默认给其名称加个s（大声告诉我不止我一个人有数组名称使用复数的强迫症，(*^__^*) 嘻嘻……）。以上是我使用后的两点建议，希望可以把这个好用的轮子造得越来越好。

**Comment by EnjoySR** [comment]
你好，能把你的第一点用于生成的JSON贴出来我看看吗？

**Comment by ghost** [comment]
你好，就是你demo展示的第二个json，比较长的那个

**Comment by EnjoySR** [comment]
这个功能已修复。关于有数组属性是否给属性key如果自动加一个s的情况，其实这个功能实现起来不难，但是自动给key加个s的话，MJExtension就不能直接解析出来的。你如果非常想要这个功能的话，我抽时间给你弄一个设置的地方，然后更新完毕通知你。谢谢你

**Comment by ghost** [comment]
O(∩_∩)O哈哈~，不用麻烦了，我自个儿手动加吧，能不能留个QQ方便我后面请教下你开发相关的问题呢

**Comment by EnjoySR** [comment]
519273266
