### ISSUE TITLE
@class ; ？？？这个哪里出了的？

### ISSUE THREAD

**Issue by zdrjson** [EnjoySR/ESJsonFormat-Xcode#24]

**Comment by EnjoySR** [comment]
把你格式化的JSON贴出来看看

**Comment by zdrjson** [comment]
{
      "apply_limit" : "0.0000",
      "assurance_id" : "101172",
      "bad_rate" : "0.2000",
      "bad_ratio" : "0",
      "collateral_address_id" : null,
      "collateral_id" : "100551",
      "collateral_price" : "0.0000",
      "collect_count" : "10000000.0000",
      "collect_interest" : "0.0000",
      "contract_info_tid" : "5932",
      "create_time" : "2015-07-16 11:00:35",
      "creditor_card_number" : null,
      "creditor_name" : null,
      "creditor_user_id" : null,
      "debt_certification_id" : null,
      "good_rate" : "0.1200",
      "good_ratio" : "0.0000",
      "id" : "267",
      "img2_ids" : null,
      "img_ids" : null,
      "interest_next_day" : "1",
      "interest_time" : "0000-00-00",
      "interest_time_limit" : "3",
      "interest_type" : "30",
      "investment_max" : null,
      "investment_quota" : null,
      "is_complete" : "0",
      "lender_account_tid" : "1564",
      "lender_user" : null,
      "lender_user_tid" : "15",
      "make_interest_plan" : "1",
      "memo" : null,
      "min_loan" : "100000.0000",
      "normal_rate" : "0.1600",
      "normal_ratio" : "10000000",
      "off_line_count" : "0",
      "off_line_time" : null,
      "order_no" : "1",
      "proceeds_of_payment_id" : "100058",
      "product_account_tid" : "1563",
      "product_info_tid" : "5933",
      "product_manager_tid" : null,
      "product_name" : "testzybq",
      "product_notes_tid" : "5934",
      "product_report" : null,
      "product_risk_tid" : "5935",
      "product_safeplan_tid" : "5936",
      "product_states_id" : "100051",
      "product_timeplan_tid" : "5937",
      "product_type_id" : "101213",
      "project_area" : null,
      "project_area_id" : "100066",
      "project_end_time" : "2015-10-16 00:00:00",
      "project_id" : "test6758",
      "project_start_time" : "2015-07-16 00:00:00",
      "raise_end_time" : "2015-10-01 00:00:00",
      "raise_start_time" : "2015-07-10 00:00:00",
      "real_collect_count" : "5890000.0000",
      "setp_loan" : "100000.0000",
      "time_limit" : "92"
    }

**Comment by zdrjson** [comment]
服务器返回这个属性比较多，看的眼花缭乱，是否在生成model的 .h或者.swfit文件中开头部分,注释好属性个数和属性类型的？比如 /*\* 20个NSString类型的属性，10个int类型的属性...*/

**Comment by EnjoySR** [comment]
修复@class为空的问题。先关闭这个。关闭你上面提的这个功能，实用性不太高，一般的话只会关注这个属性是干什么的，应该不会关注属性个数，这个功能我会考虑的，谢谢
