### ISSUE TITLE
如果已经生成这个model文件,再次生成同名model文件，你直接覆盖？

### ISSUE THREAD

**Issue by zdrjson** [EnjoySR/ESJsonFormat-Xcode#28]

**Comment by EnjoySR** [comment]
请交流的时候不要以反问的语气，这只会让别人很不爽。你提的这么建议，我感激你，但是不知道你有没有发现你提一这一些建设，里面很很多话把都是以这种语气来交流的。当然你这个问题，我也可以以反问的语气回答你：你自己不会看啊？ 你的感觉呢？

**Comment by zdrjson** [comment]
OK，你不能直接覆盖，应该提示！
