### ISSUE TITLE
急，请问这是什么原因。

### ISSUE THREAD

**Issue by weizhangCoder** [EnjoySR/ESJsonFormat-Xcode#38]
原来我这种格式的是可以转化的
{
        "buy_num" = 596;
        discount = "10.0";
        finalPrice = "9.9";
        "is_collect" = n;
        "is_today" = n;
        numIid = 45711009510;
        "pub_time" = "2015-09-01 17:00";
        reservePrice = "9.9";
    }
现在突然发现转化会报格式错误，报The data couldn’t be read because it isn’t in the correct format.。
不过你列举的那个json是可以转化的，

**Comment by weizhangCoder** [comment]
不好意思，我知道怎么回事了，我的问题，

**Comment by EnjoySR** [comment]
嗯嗯谢谢
