### ISSUE TITLE
用着很方便，提个 bug，希望作者有时间的话可以改进一下

### ISSUE THREAD

**Issue by LLLX77** [EnjoySR/ESJsonFormat-Xcode#39]
这是我从新浪API 接口中返回的 JSON 数据中的一段：
"statuses": [
        {
            "created_at": "Tue May 31 17:46:55 +0800 2011",
            "id": 11488058246,
            "text": "求关注。",
            "source": "<a href="http://weibo.com" rel="nofollow">新浪微博</a>",

问题出在 source 这里，source 对应的 value 中包含了多个引号 “” ，应该是不能正确识别了，一直报错误：The data couldn’t be read because it isn’t in the correct format. 去掉这行之后就可以正确转换，希望作者有时间的话可以改进一下这个小 bug，用着真的挺方便的，感谢。

**Comment by EnjoySR** [comment]
这不是一个正确的JSON，有经验的后台是不会这样返回的哟。而且你可以去请求新浪微博官方的数据，也不是这样返回的。你可以去看看。谢谢你的反馈
