### ISSUE TITLE
属性很多，生成后，中间会冒出很多空行？？？

### ISSUE THREAD

**Issue by zdrjson** [EnjoySR/ESJsonFormat-Xcode#4]

**Comment by EnjoySR** [comment]
你是想每个属性之间不需要有空行么？我可能后面会更新支持属性的注释，就是直接在json里面直接在指定字段后面写上注释，然后生成之后直接该属性上面就有对应的注释，所以＝＝，下次更新我把注释加上，然后如果该字段后面没有注释的话我就直接不与上面的属性换行。请你持续关注，谢谢你。

**Comment by zdrjson** [comment]
需要的，需要空行，每个属性之间空一行就够了，最好能加上注释，发现有时候属性之间空很多行，弄得没有规律，你自己试试，属性很多的时候！

**Comment by EnjoySR** [comment]
嗯，谢谢你的反馈，我找到问题之后尽快修复

**Comment by EnjoySR** [comment]
中间生成多个空行的bug已修复，原因是json里面某个key对应的value是NSNull，所以返回了更多空行。现在如果json里面key对应的value是NSNull的话默认以NSString显示。请更新。有问题请继续Issues我。非常感谢
