### ISSUE TITLE
json格式能否可编辑

### ISSUE THREAD

**Issue by iGenMO** [EnjoySR/ESJsonFormat-Xcode#40]
{
            createName = "";
            createTime = "";
            hotSearchId = 10;
            hotSearchName = "\U5546\U5bb65";
            hotSearchType = 0;
            memo = "";
            updateName = "";
            updateTime = "";
 }

您好,目前所用的格式是这样,一直提示格式错误,能否增加格式编辑功能?

**Comment by EnjoySR** [comment]
这个是NSDictionary输出description的格式，插件是不支持这种格式的。只支持JSON。谢谢你的反馈
