### ISSUE TITLE
啥时候能解析这个

### ISSUE THREAD

**Issue by dymost** [EnjoySR/ESJsonFormat-Xcode#47]
{
    PicUrl : /upFile/house/loupan/20151015/20151015235322_7825.jpg,
    TJHX : 2室90平,3室117平,
    MapX : ,
    fyhao : 4,
}

有一个 空值,
键和值 中的字符串都没有双引号 不能识别

**Comment by EnjoySR** [comment]
😂 这不是一个合法的JSON。。～～所以解析不了
