### ISSUE TITLE
亲，能加入注释？？？中间的

### ISSUE THREAD

**Issue by zdrjson** [EnjoySR/ESJsonFormat-Xcode#5]
/*\* <#Description#>_/
@property (nonatomic,copy) NSString \* a;
/_\* <#Description#>_/
@property (nonatomic,assign) BOOL b;
/__<#Description#>_/
@property (nonatomic,copy) NSString \* c;

**Comment by EnjoySR** [comment]
我的想法是直接就在输入json的那个对话框里面，直接在输入json的时候，json里面对应字段的后面打两个斜线然后后面写上注释，生成完毕之后就是带有注释的，想哪个有注释你就在json里面后面对应字段后面写注释就行了，这样更方便，你觉得我这样的想法行不行，谢谢你的建议，我们共同商讨完善。

**Comment by zdrjson** [comment]
如果是json数据，但不是json正规格式，你能自己校验吗？

**Comment by EnjoySR** [comment]
如果这样的话，我就不知道怎么去校验了，因为可能会出现各种不同的格式，你这边可能是一种格式，另外的人可能是另一种格式，这个就不好实现了。

**Comment by zdrjson** [comment]
应该学习下bejson是怎么校验的

**Comment by EnjoySR** [comment]
能给我看看你说的那种格式嘛

**Comment by zdrjson** [comment]
生成的MJExtension 2.0框架中objectClassInArray方法(类方法) 怎么用？你得把用法写出来？

**Comment by EnjoySR** [comment]
这个功能是与MJExtension框架中的那个方法一样的，是告诉数组里面装的是哪个模型，生成的格式是直接适配MJExtension的，你如果用过MJExtension的话应该就清楚了。链接：[MJExtension](https://github.com/CoderMJLee/MJExtension)
