### ISSUE TITLE
xcode 7.2不支持

### ISSUE THREAD

**Issue by d553296416** [EnjoySR/ESJsonFormat-Xcode#54]
xcode 7.2不支持 更换了uuid后提示The operation couldn’t be completed. (Current state is not edit! error 0.)

**Comment by huoyingjie** [comment]
是啊，我也再等更新，7.2不能用了。

**Comment by d553296416** [comment]
不，我提示了几次The operation couldn’t be completed. 又奇迹般好了

**Comment by huoyingjie** [comment]
我的还不行，😓，没有一点反应

发自我的 iPhone

**Comment by mifanj** [comment]
更换udid成功解决

**Comment by huoyingjie** [comment]
@mifanj  能简单描述下步骤么，多谢啊！

**Comment by mifanj** [comment]
@huoyingjie http://www.jianshu.com/p/db3d34a54031 教程链接

**Comment by huoyingjie** [comment]
@mifanj 3Q我先试试

**Comment by huoyingjie** [comment]
@mifanj 完美👍

**Comment by mifanj** [comment]
@huoyingjie 我也是听别的大神说的

**Comment by bigParis** [comment]
不知道你们用的是什么版本,我现在用的是可以的

**Comment by EnjoySR** [comment]
😂

**Comment by myHeartGo** [comment]
啦啦啦啦啦

**Comment by myHeartGo** [comment]
啦啦啦啦啦啦啦
