### ISSUE TITLE
复杂的json是不是就不可以了比如说这样的

### ISSUE THREAD

**Issue by tztTztTzt** [EnjoySR/ESJsonFormat-Xcode#63]
{
    data =     {
        "created_at" = "2016-03-16 16:17:05",
        "from_id" = 396,
        "from_user" =         {
            avatar = "uploads/1/396/avatar/08c810728c81322d.jpg",
            city = "\U676d\U5dde\U5e02",
            "created_at" = "2016-01-13 20:52:56",
            email = "2029358592@qq.com",
            gender = 1,
            id = 396,
            introduce = aaa,
            "invite_code" = r8rrx,
            "invited_by_user_id" = 0,
            mobile = 15068791550,
            "openim_name" = 15068791550,
            "openim_pass" = 9d87311a1d0153f5620d1af4e138de16,
            position = student,
            role = 0,
            status = 1,
            tags = "[{\"id\":\"97\",\"name\":\"\u6570\u5b66\",\"type\":1},{\"id\":\"101\",\"name\":\"\u5316\u5b66\",\"type\":1},{\"id\":\"198\",\"name\":\"\u793c\u4eea\u6a21\u7279\",\"type\":2}]",
            taobaoid = "",
            trade = Gg,
            university = "",
            "updated_at" = "2016-03-08 13:29:11",
            userid = "",
            userinfos = "",
            username = 15068791550,
            workplace = "",
        },
        id = 96,
        post =         {
            content = "\U6211\U516c\U516c",
            cover = "uploads/1/19/cover/e04033544607b9e0.jpg",
            "created_at" = "2016-03-14 18:12:24",
            endtime = "2016-03-16 18:12:00",
            id = 204,
            "is_commented" = 1,
            latitude = "30.280979",
            location = "\U6d59\U6c5f\U7701\U676d\U5dde\U5e02\U897f\U6e56\U533a\U5858\U82d7\U8def18\U53f7-b105",
            longitude = "120.127705",
            "max_people" = "-1",
            pic = "",
            properties = "{\"tag\":\"\u751f\u6d3b\u5468\u8fb9\",\"publish\":\"\u4e2a\u4eba\"}",
            "publish_id" = 51,
            recommendable = 0,
            starttime = "2016-03-14 18:12:24",
            status = 1,
            "tag_id" = 62,
            title = "\U54c8\U54c8\U54c8\U5475\U5475",
            type = 2,
            "updated_at" = "2016-03-14 18:12:24",
            user =             {
                avatar = "uploads/1/19/avatar/5bddee90b4473149.",
                city = "\U676d\U5dde\U5e02",
                "created_at" = "2015-09-14 07:46:54",
                email = "ydpeng@sokiwi.com",
                gender = 1,
                id = 19,
                introduce = "\U65e0\U754f\Uff0c\U4e0d\U65e0\U77e5\U3002",
                "invite_code" = r8q4m,
                "invited_by_user_id" = 0,
                mobile = 13296669001,
                "openim_name" = 13296669001,
                "openim_pass" = 34f0d00660c74af65d832d17c131940e,
                position = student,
                role = 0,
                status = 1,
                tags = "[{\"id\":\"119\",\"name\":\"\u7d20\u63cf\",\"type\":1},{\"id\":\"191\",\"name\":\"\u56fd\u5b66\",\"type\":1},{\"id\":\"198\",\"name\":\"\u793c\u4eea\u6a21\u7279\",\"type\":2},{\"id\":\"201\",\"name\":\"\u6b66\u672f\",\"type\":2}]",
                taobaoid = "",
                trade = "\U793c\U4eea\U6a21\U7279",
                university = "",
                "updated_at" = "2016-03-16 14:12:00",
                userid = "",
                userinfos = "",
                username = 13296669001,
                workplace = "",
            },
            "user_id" = 19,
            views = 4,
        },
        "post_id" = 204,
        status = 0,
        "to_id" = 399,
        "updated_at" = "2016-03-16 16:17:05",
    },
    success = true,
}

**Comment by dustturtle** [comment]
这不是复杂不复杂的问题，是json不标准的问题。这里可以解决你的问题：
https://github.com/dustturtle/ESJsonFormat-Xcode

**Comment by EnjoySR** [comment]
楼上机智
