### ISSUE TITLE
7.3不能用了，需要更新下

### ISSUE THREAD

**Issue by hiETsang** [EnjoySR/ESJsonFormat-Xcode#64]
**今天手贱更新了iOS9.3，顺手又更新了Xcode7.3，额，现在不能用了**

**Comment by britzlieg** [comment]
关掉XCode，运行一下terminal命令，重新打开是选择Load Bundle:

find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID`

**Comment by hiETsang** [comment]
试了一下，还是不行啊

**Comment by britzlieg** [comment]
要将命令输入多几次，第一次我也不行

**Comment by britzlieg** [comment]
http://joeshang.github.io/2015/04/10/fix-xcode-upgrade-plugin-invalid/

**Comment by hiETsang** [comment]
好的我试试  谢谢

**Comment by britzlieg** [comment]
有时可能要先把旧的移除掉，彻底关掉XCode，然后运行命令，然后再安装。具体步骤也就这几步，你可以试下

**Comment by Ohuisang** [comment]
@britzlieg  看了博客原文：**你粘贴的命令行 被 markdown 格式化掉了两个点了**

```
 find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID`
```

**Comment by boai** [comment]
用这个可以，前提要关掉xcode，然后终端运行，一次不行，运行两次！
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info.plist DVTPlugInCompatibilityUUID`

**Comment by boai** [comment]
看这个！http://www.cnblogs.com/boai/p/5312631.html

**Comment by kyleduo** [comment]
赞👍

**Comment by RondaHe** [comment]
升级xcode插件失效解决方案 [http://www.jianshu.com/p/6fc1a6cbf4fe](http://www.jianshu.com/p/6fc1a6cbf4fe)

**Comment by EnjoySR** [comment]
感谢各位！
