### ISSUE TITLE
总是提示格式不对

### ISSUE THREAD

**Issue by taitanxiami** [EnjoySR/ESJsonFormat-Xcode#8]
{
cluId: 2,
effectiveLastTime: 1438223201000,
id: 3,
money: 100,
sequence: "desc",
showTime: "2015-07-02 10:26",
status: 0,
time: 1435804008000,
title: "优惠券"
}

**Comment by taitanxiami** [comment]
一般是在web 用jsonview 产看数据结构的，粘贴过来不行

**Comment by EnjoySR** [comment]
这不是一个合法的json，key需要有引号引起来才行。json校验网址：http://www.kjson.com/ 或者 http://www.bejson.com/

**Comment by taitanxiami** [comment]
好的

**Comment by EnjoySR** [comment]
那我先close这个，有问题继续Issues我。谢谢你的关注。
