### ISSUE TITLE
XCode8把插件干掉了，这个项目能否独立成工具？

### ISSUE THREAD

**Issue by Neojoke** [EnjoySR/ESJsonFormat-Xcode#81]
如题

**Comment by Neojoke** [comment]
独立成脚本也成

**Comment by EnjoySR** [comment]
see [https://github.com/Ahmed-Ali/JSONExport](https://github.com/Ahmed-Ali/JSONExport)

**Comment by lilin87788** [comment]
谢谢

**Comment by Jinxiansen** [comment]
不明白转 oc Model 的时候为什么不是用 copy 来修饰字符串。
还有 Swift 为什么 var 都是 ！而不是？来修饰。
