### ISSUE TITLE
xcode8

### ISSUE THREAD

**Issue by Easyzhan** [EnjoySR/ESJsonFormat-Xcode#82]
这个还可以用吗

**Comment by paopaosa** [comment]
有支持Xcode Source Editor Extension 的计划吗？

**Comment by DreamBuddy** [comment]
没有了ESJsonFormatt 开发 好痛苦啊。。谢谢作者

**Comment by EnjoySR** [comment]
有的，到时候更新了我@你们，主要是现在Xcode Source Editor Extension这个太不稳定了，运行起来之后在菜单里面有很大的概率不会出现触发的item.

**Comment by lzhlewis2015** [comment]
作者你好，Xcode Source Editor Extension 现在有开发的版本可以先给我们用用吗，就算不出现触发的item也好。。。 不然自己敲代码太麻烦了  有的话可以发一份给我吗 我的邮箱是160264075@qq.com

**Comment by EnjoySR** [comment]
@lzhlewis2015 https://github.com/fpg1503/MakeXcodeGr8Again 你试试这个

**Comment by keepyounger** [comment]
我参考这个做了个支持 Xcode 8 的，大家可以先用我的[Json2Property](https://github.com/keepyounger/Json2Property)救急。同时感谢 @EnjoySR

**Comment by EnjoySR** [comment]
see https://github.com/Ahmed-Ali/JSONExport
@keepyounger @Easyzhan @paopaosa @xmt0615 @lzhlewis2015 2015

**Comment by DreamBuddy** [comment]
@EnjoySR 这个试用过，没ESJson方便 配合MJExtension不好用

**Comment by DreamBuddy** [comment]
@EnjoySR 大神您好！。。用您的源码 改了点东西 重新编译出来的残次品 但是能凑活用 独立于 Xcode 单独运行
[ESJSonFormatter.zip](https://github.com/EnjoySR/ESJsonFormat-Xcode/files/555639/ESJSonFormatter.zip)

@keepyounger @Easyzhan @lzhlewis2015

**Comment by hstdt** [comment]
@xmt0615  你好,请问能否把你的软件的系统要求降低一些,目前我还在用10.11.6.谢谢!

**Comment by DreamBuddy** [comment]
@hstdt 可以！今晚下班后我搞下吧 正好优化下

**Comment by veryitman** [comment]
@DreamBuddy 能给我一个吗? veryitman@126.com

**Comment by mengruirui** [comment]
你好，能否给我一个？链接下载不了。18513567072@163.com

**Comment by mengruirui** [comment]
@DreamBuddy 能给我一个吗？链接下载不了。18513567072@163.com 谢谢了。

**Comment by EnjoySR** [comment]
Xcode8及之后使用插件见：http://www.cocoachina.com/ios/20161207/18313.html
