### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by wliu6** [EnjoySR/ESJsonFormat-Xcode#87]
感谢ESJsonFormat，伴我很长长时间的开发时光，Xcode8后原来的插件植入方式都不能用了，所以萌生了一个idea，写了个小脚本调用mac系统的GUI实现了和ESJsonFormat类似的功能，望大神不吝赐教，提出缺陷以便改正并帮助众多码农同志。（仓库地址：https://github.com/wliu6/OC_JSON_Plugin）

**Comment by EnjoySR** [comment]
Xcode8及之后使用插件见：http://www.cocoachina.com/ios/20161207/18313.html
