### ISSUE TITLE
xcode7 bate 使用不了

### ISSUE THREAD

**Issue by SuperDannyBoy** [EnjoySR/ESJsonFormat-Xcode#9]

**Comment by EnjoySR** [comment]
打开finder，找到应用程序，然后右键点击Xcode 7，选择显示包内容，content，打开info.plist，把DVTPlugInCompatibilityUUID后面对应的value发给我，谢谢你了，然后我添加上去就可以使用了。

**Comment by randomprocess** [comment]
我现在用的是 Xcode Beta 6.3 , 对应的DVTPlugInCompatibilityUUID是 "992275C1-432A-4CF7-B659-D84ED6D42D3F"  
在安放好插件后直接打开.xcodeproj没出问题只是插件不能使用.  不过在打开.xcworkspace的时候就无限小菊花只能强制退出. 之后我将DVTPlugInCompatibilityUUID添加后可以正常打开.xcworkspace了. 以上是我遇到到一点小问题, 仅供参考~

**Comment by EnjoySR** [comment]
@randomprocess 非常感谢你的反馈以及你的关注。

**Comment by SuperDannyBoy** [comment]
@EnjoySR AABB7188-E14E-4433-AD3B-5CD791EAD9A3

**Comment by EnjoySR** [comment]
It's ok,please update.Thank you for your attention.
